//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AC_Telefonbuch.Properties
{
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.0.0.4516")]
	internal sealed partial class Application : global::System.Configuration.ApplicationSettingsBase
	{
		
		private static Application defaultInstance = ((Application)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Application())));
		
		public static Application Default
		{
			get
			{
				return defaultInstance;
			}
		}
		
		/// <summary>
		/// Position des Hauptfensters
		/// </summary>
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Configuration.SettingsDescriptionAttribute("Position des Hauptfensters")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
		public global::System.Drawing.Point SearchFormPosition
		{
			get
			{
				return ((global::System.Drawing.Point)(this["SearchFormPosition"]));
			}
			set
			{
				this["SearchFormPosition"] = value;
			}
		}
		
		/// <summary>
		/// Größe des Hauptfensters
		/// </summary>
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Configuration.SettingsDescriptionAttribute("Größe des Hauptfensters")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
		public global::System.Drawing.Size SearchFormSize
		{
			get
			{
				return ((global::System.Drawing.Size)(this["SearchFormSize"]));
			}
			set
			{
				this["SearchFormSize"] = value;
			}
		}
		
		/// <summary>
		/// Quelldatei für Anzeige und Suche
		/// </summary>
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Configuration.SettingsDescriptionAttribute("Quelldatei für Anzeige und Suche")]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Data\\AC-Kontakte Gesamt.csv")]
		public string sourceFile
		{
			get
			{
				return ((string)(this["sourceFile"]));
			}
			set
			{
				this["sourceFile"] = value;
			}
		}
	}
}
